#!/usr/bin/env bash
echo 'your name in github'
read name
echo 'new repo name'
read repo
echo 'destination folder'
read dest
cd "${dest//'~'/$HOME}"
git clone "git://github.com/WebReflection/gitstrap.git" "$repo"
cd "$repo"
rm -rf .git
MAKEFILE=`cat Makefile`
echo "${MAKEFILE/REPO = main/REPO = ${repo}}" >Makefile
PACKAGE=`cat package.json`
PACKAGE_NOMAIN="${PACKAGE//main/${repo}}"
PACKAGE_MAINBIN="${PACKAGE_NOMAIN/\"${repo}\":/\"main\":}"
echo "${PACKAGE_MAINBIN//WebReflection/${name}}" >package.json
INDEX=`cat index.html`
echo "${INDEX/TESTS = [\"main\"]/TESTS = [\"${repo}\"]}" >index.html
LICENSE=`cat LICENSE.txt`
echo "${LICENSE/WebReflection/${name}}" >LICENSE.txt
COPYRIGHT=`cat template/copyright`
echo "${COPYRIGHT/WebReflection/${name}}" >template/copyright
REPO_NAME_LENGTH=$(printf "%${#repo}s")
echo "${repo}
${REPO_NAME_LENGTH// /=}

[![build status](https://secure.travis-ci.org/${name}/${repo}.png)](http://travis-ci.org/${name}/${repo})
" >README.md
TEST=`cat test/main.js`
echo "${TEST//main.node.js/${repo}.node.js}" >test/${repo}.js
rm test/main.js
mv src/main.js src/${repo}.js
make dependencies
make clean
make var
make node
make amd
git init
git add .
git commit -m "${repo} gitstrap initialized"
git remote add origin "git@github.com:${name}/${repo}.git"
echo '------------------------------------'
echo "your new ${repo} repository is ready"
echo '------------------------------------'
echo ''
echo 'do you want to push now ? (y/n)'
read pushorigin
if [ "$pushorigin" = "y" ]; then
  git push -u origin master
fi
make test
exit 0
